[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npx playwright install chromium --with-deps && npm run build"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npm start"
restartPolicyType = "on_failure"

